import Head from "next/head";
import { useEffect } from "react";
import Banner from "../components/Banner";
import Header from "../components/Header";
import Top from "../components/Top";
import Popular from "../components/Popular";

export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>Movie test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#182131]">
        <Header />
      </div>
      <Banner />
      <Popular />
      <Top />
    </div>
  );
}
